"""mock sessions transcripts and feedback

Revision ID: 5ca6ea8ad93d
Revises: 55716c3e3677
Create Date: 2026-08-16 12:20:53.012440+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "5ca6ea8ad93d"
down_revision: str | None = "55716c3e3677"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcript_segments",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("session_kind", sa.String(length=8), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("speaker_role", sa.String(length=16), nullable=False),
        sa.Column("speaker_label", sa.String(length=64), nullable=True),
        sa.Column("start_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("end_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_final", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "session_kind IN ('mock','live')",
            name=op.f("ck_transcript_segments_transcript_segments_kind_valid"),
        ),
        sa.CheckConstraint(
            "speaker_role IN ('candidate','interviewer','unknown')",
            name=op.f("ck_transcript_segments_transcript_segments_role_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_transcript_segments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
        sa.UniqueConstraint("session_id", "seq", name="uq_transcript_segments_session_seq"),
    )
    op.create_index(
        "ix_transcript_segments_session", "transcript_segments", ["session_id", "seq"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_segments_user_id"), "transcript_segments", ["user_id"], unique=False
    )
    op.create_table(
        "mock_sessions",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("persona", sa.String(length=32), nullable=False),
        sa.Column("difficulty", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("planned_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=20), server_default="en-US", nullable=False),
        sa.Column("live_feedback", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("context_version", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="created", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("end_reason", sa.String(length=48), nullable=True),
        sa.Column(
            "interviewer_state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "difficulty BETWEEN 1 AND 5",
            name=op.f("ck_mock_sessions_mock_sessions_difficulty_range"),
        ),
        sa.CheckConstraint(
            "planned_duration_seconds BETWEEN 60 AND 7200",
            name=op.f("ck_mock_sessions_mock_sessions_duration_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_mock_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_mock_sessions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mock_sessions")),
    )
    op.create_index(
        op.f("ix_mock_sessions_created_at"), "mock_sessions", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_mock_sessions_user_id"), "mock_sessions", ["user_id"], unique=False)
    op.create_index(
        "ix_mock_sessions_user_recent",
        "mock_sessions",
        ["user_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_mock_sessions_workspace_id"), "mock_sessions", ["workspace_id"], unique=False
    )
    op.create_table(
        "question_attempts",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("session_kind", sa.String(length=8), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("intent", sa.String(length=16), server_default="question", nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "scores",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "delivery",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("story_id", sa.UUID(), nullable=True),
        sa.Column("prompt_ref", sa.String(length=120), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["candidate_stories.id"],
            name=op.f("fk_question_attempts_story_id_candidate_stories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_question_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_question_attempts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_attempts")),
        sa.UniqueConstraint("session_id", "sequence", name="uq_question_attempts_session_seq"),
    )
    op.create_index(
        op.f("ix_question_attempts_created_at"), "question_attempts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_question_attempts_session_id"), "question_attempts", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_question_attempts_user_id"), "question_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "session_feedback",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("session_kind", sa.String(length=8), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "dimension_scores",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "delivery_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "strengths",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "weaknesses",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "recommendations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "per_question",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("rubric_version", sa.String(length=32), nullable=False),
        sa.Column("prompt_ref", sa.String(length=120), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="processing", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 100)",
            name=op.f("ck_session_feedback_session_feedback_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_session_feedback_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_session_feedback_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_feedback")),
        sa.UniqueConstraint("session_id", "session_kind", name="uq_session_feedback_session"),
    )
    op.create_index(
        op.f("ix_session_feedback_created_at"), "session_feedback", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_session_feedback_user_id"), "session_feedback", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_session_feedback_workspace_id"), "session_feedback", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_feedback_workspace_id"), table_name="session_feedback")
    op.drop_index(op.f("ix_session_feedback_user_id"), table_name="session_feedback")
    op.drop_index(op.f("ix_session_feedback_created_at"), table_name="session_feedback")
    op.drop_table("session_feedback")
    op.drop_index(op.f("ix_question_attempts_user_id"), table_name="question_attempts")
    op.drop_index(op.f("ix_question_attempts_session_id"), table_name="question_attempts")
    op.drop_index(op.f("ix_question_attempts_created_at"), table_name="question_attempts")
    op.drop_table("question_attempts")
    op.drop_index(op.f("ix_mock_sessions_workspace_id"), table_name="mock_sessions")
    op.drop_index(
        "ix_mock_sessions_user_recent",
        table_name="mock_sessions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_mock_sessions_user_id"), table_name="mock_sessions")
    op.drop_index(op.f("ix_mock_sessions_created_at"), table_name="mock_sessions")
    op.drop_table("mock_sessions")
    op.drop_index(op.f("ix_transcript_segments_user_id"), table_name="transcript_segments")
    op.drop_index("ix_transcript_segments_session", table_name="transcript_segments")
    op.drop_table("transcript_segments")
    # ### end Alembic commands ###
