"""preparation plans and tasks

Revision ID: 55716c3e3677
Revises: 67e71ce1101a
Create Date: 2026-08-16 11:52:38.720836+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "55716c3e3677"
down_revision: str | None = "67e71ce1101a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preparation_plans",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("round_index", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("stage", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("generated_by", sa.String(length=64), nullable=False),
        sa.Column(
            "summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("context_version", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "round_index > 0", name=op.f("ck_preparation_plans_preparation_plans_round_positive")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_preparation_plans_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_preparation_plans_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preparation_plans")),
        sa.UniqueConstraint(
            "workspace_id", "round_index", "version", name="uq_preparation_plans_round_version"
        ),
    )
    op.create_index(
        op.f("ix_preparation_plans_created_at"), "preparation_plans", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_preparation_plans_user_id"), "preparation_plans", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_preparation_plans_workspace_id"),
        "preparation_plans",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "preparation_tasks",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("section", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("priority_score", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column(
            "score_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "action",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), server_default=sa.text("15"), nullable=False),
        sa.Column("scheduled_for", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=16), server_default="plan", nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "priority IN ('critical','high','medium','optional')",
            name=op.f("ck_preparation_tasks_preparation_tasks_priority_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('open','in_progress','done','dismissed')",
            name=op.f("ck_preparation_tasks_preparation_tasks_status_valid"),
        ),
        sa.CheckConstraint(
            "estimated_minutes > 0",
            name=op.f("ck_preparation_tasks_preparation_tasks_minutes_positive"),
        ),
        sa.CheckConstraint(
            "priority_score >= 0 AND priority_score <= 1",
            name=op.f("ck_preparation_tasks_preparation_tasks_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["preparation_plans.id"],
            name=op.f("fk_preparation_tasks_plan_id_preparation_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_preparation_tasks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_preparation_tasks_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preparation_tasks")),
        sa.UniqueConstraint("plan_id", "dedupe_key", name="uq_preparation_tasks_plan_dedupe"),
    )
    op.create_index(
        op.f("ix_preparation_tasks_created_at"), "preparation_tasks", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_preparation_tasks_plan_id"), "preparation_tasks", ["plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_preparation_tasks_user_id"), "preparation_tasks", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_preparation_tasks_workspace_id"),
        "preparation_tasks",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_preparation_tasks_workspace_ranked",
        "preparation_tasks",
        ["workspace_id", "status", "priority_score"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_preparation_tasks_workspace_ranked", table_name="preparation_tasks")
    op.drop_index(op.f("ix_preparation_tasks_workspace_id"), table_name="preparation_tasks")
    op.drop_index(op.f("ix_preparation_tasks_user_id"), table_name="preparation_tasks")
    op.drop_index(op.f("ix_preparation_tasks_plan_id"), table_name="preparation_tasks")
    op.drop_index(op.f("ix_preparation_tasks_created_at"), table_name="preparation_tasks")
    op.drop_table("preparation_tasks")
    op.drop_index(op.f("ix_preparation_plans_workspace_id"), table_name="preparation_plans")
    op.drop_index(op.f("ix_preparation_plans_user_id"), table_name="preparation_plans")
    op.drop_index(op.f("ix_preparation_plans_created_at"), table_name="preparation_plans")
    op.drop_table("preparation_plans")
    # ### end Alembic commands ###
