"""workspaces and context bundle

Revision ID: 67e71ce1101a
Revises: 25f29e60d9a5
Create Date: 2026-08-16 09:11:44.025937+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "67e71ce1101a"
down_revision: str | None = "25f29e60d9a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("role_title", sa.String(length=200), nullable=False),
        sa.Column("role_family", sa.String(length=64), nullable=True),
        sa.Column("seniority", sa.String(length=32), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("resume_version_id", sa.UUID(), nullable=True),
        sa.Column("stage", sa.String(length=24), server_default="preparing", nullable=False),
        sa.Column("round_index", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("interview_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column(
            "integrity_mode", sa.String(length=16), server_default="assisted", nullable=False
        ),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("readiness_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("readiness_computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "integrity_mode IN ('assisted','proctored')",
            name=op.f("ck_workspaces_workspaces_integrity_valid"),
        ),
        sa.CheckConstraint(
            "stage IN ('preparing','recruiter_screen','hiring_manager','technical','onsite','final','offer','rejected')",
            name=op.f("ck_workspaces_workspaces_stage_valid"),
        ),
        sa.CheckConstraint(
            "readiness_score IS NULL OR (readiness_score >= 0 AND readiness_score <= 100)",
            name=op.f("ck_workspaces_workspaces_readiness_range"),
        ),
        sa.CheckConstraint("round_index > 0", name=op.f("ck_workspaces_workspaces_round_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_workspaces_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_workspaces_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["resume_version_id"],
            ["resume_versions.id"],
            name=op.f("fk_workspaces_resume_version_id_resume_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_workspaces_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_index(op.f("ix_workspaces_company_id"), "workspaces", ["company_id"], unique=False)
    op.create_index(op.f("ix_workspaces_created_at"), "workspaces", ["created_at"], unique=False)
    op.create_index(op.f("ix_workspaces_user_id"), "workspaces", ["user_id"], unique=False)
    op.create_index(
        "ix_workspaces_user_recent",
        "workspaces",
        ["user_id", "updated_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_workspaces_user_upcoming",
        "workspaces",
        ["user_id", "interview_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND archived_at IS NULL"),
    )
    op.create_table(
        "story_workspace_overrides",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("relevance", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("tailored_opening", sa.Text(), nullable=True),
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["candidate_stories.id"],
            name=op.f("fk_story_workspace_overrides_story_id_candidate_stories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_story_workspace_overrides_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "workspace_id", "story_id", name=op.f("pk_story_workspace_overrides")
        ),
    )
    op.create_index(
        op.f("ix_story_workspace_overrides_created_at"),
        "story_workspace_overrides",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "workspace_context",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "bundle",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "match",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("stale", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workspace_context_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_context_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_context")),
        sa.UniqueConstraint("workspace_id", name=op.f("uq_workspace_context_workspace_id")),
    )
    op.create_index(
        op.f("ix_workspace_context_created_at"), "workspace_context", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_workspace_context_user_id"), "workspace_context", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspace_context_user_id"), table_name="workspace_context")
    op.drop_index(op.f("ix_workspace_context_created_at"), table_name="workspace_context")
    op.drop_table("workspace_context")
    op.drop_index(
        op.f("ix_story_workspace_overrides_created_at"), table_name="story_workspace_overrides"
    )
    op.drop_table("story_workspace_overrides")
    op.drop_index(
        "ix_workspaces_user_upcoming",
        table_name="workspaces",
        postgresql_where=sa.text("deleted_at IS NULL AND archived_at IS NULL"),
    )
    op.drop_index(
        "ix_workspaces_user_recent",
        table_name="workspaces",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_workspaces_user_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_created_at"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_company_id"), table_name="workspaces")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
