"""deletion jobs

Revision ID: 9606771e9510
Revises: 784938fd489c
Create Date: 2026-08-16 14:30:20.872396+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "9606771e9510"
down_revision: str | None = "784938fd489c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletion_jobs",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("execute_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "stores",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','running','completed','cancelled','failed')",
            name=op.f("ck_deletion_jobs_deletion_jobs_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_jobs")),
    )
    op.create_index(
        op.f("ix_deletion_jobs_created_at"), "deletion_jobs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_deletion_jobs_due",
        "deletion_jobs",
        ["execute_after"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(op.f("ix_deletion_jobs_user_id"), "deletion_jobs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deletion_jobs_user_id"), table_name="deletion_jobs")
    op.drop_index(
        "ix_deletion_jobs_due",
        table_name="deletion_jobs",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_deletion_jobs_created_at"), table_name="deletion_jobs")
    op.drop_table("deletion_jobs")
    # ### end Alembic commands ###
