"""candidate graph

Revision ID: c90d355cf068
Revises: c16939064b55
Create Date: 2026-08-16 08:17:09.143123+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c90d355cf068"
down_revision: str | None = "c16939064b55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_profiles",
        sa.Column("headline", sa.String(length=300), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("experience_level", sa.String(length=24), nullable=True),
        sa.Column("target_role", sa.String(length=200), nullable=True),
        sa.Column("role_family", sa.String(length=64), nullable=True),
        sa.Column(
            "target_industries",
            postgresql.ARRAY(sa.String(length=80)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("goal", sa.String(length=32), nullable=True),
        sa.Column("contact_enc", sa.LargeBinary(), nullable=True),
        sa.Column(
            "style_profile",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "experience_level IS NULL OR experience_level IN ('student','entry','mid','senior','staff','manager','director','exec')",
            name=op.f("ck_candidate_profiles_candidate_profiles_level_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_candidate_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_profiles")),
        sa.UniqueConstraint("user_id", name="uq_candidate_profiles_user_id"),
    )
    op.create_index(
        op.f("ix_candidate_profiles_created_at"), "candidate_profiles", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_candidate_profiles_user_id"), "candidate_profiles", ["user_id"], unique=False
    )
    op.create_table(
        "candidate_stories",
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column(
            "categories",
            postgresql.ARRAY(sa.String(length=40)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("situation", sa.Text(), nullable=True),
        sa.Column("task", sa.Text(), nullable=True),
        sa.Column(
            "actions", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "skills_demonstrated",
            postgresql.ARRAY(sa.String(length=120)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "roles_relevant_to",
            postgresql.ARRAY(sa.String(length=80)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "source_experience_ids",
            postgresql.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "source_evidence_ids",
            postgresql.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("speak_time_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "variants",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), server_default="suggested", nullable=False),
        sa.Column("usage_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('suggested','approved','rejected','needs_detail')",
            name=op.f("ck_candidate_stories_candidate_stories_status_valid"),
        ),
        sa.CheckConstraint(
            "speak_time_seconds IS NULL OR speak_time_seconds > 0",
            name=op.f("ck_candidate_stories_candidate_stories_speak_time_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_candidate_stories_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_stories")),
    )
    op.create_index(
        "ix_candidate_stories_categories",
        "candidate_stories",
        ["categories"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_candidate_stories_created_at"), "candidate_stories", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_candidate_stories_status"), "candidate_stories", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_candidate_stories_user_id"), "candidate_stories", ["user_id"], unique=False
    )
    op.create_index(
        "ix_candidate_stories_user_status",
        "candidate_stories",
        ["user_id", "status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "certifications",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("issuer", sa.String(length=200), nullable=True),
        sa.Column("issued_on", sa.Date(), nullable=True),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("credential_id", sa.String(length=160), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending_review", nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column("extracted_by", sa.String(length=120), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "user_corrected",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('resume','user_manual','jd','session_transcript','user_note','inference')",
            name=op.f("ck_certifications_certifications_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft','pending_review','approved','rejected','superseded')",
            name=op.f("ck_certifications_certifications_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_certifications_certifications_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_certifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certifications")),
    )
    op.create_index(
        op.f("ix_certifications_created_at"), "certifications", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_certifications_status"), "certifications", ["status"], unique=False)
    op.create_index(op.f("ix_certifications_user_id"), "certifications", ["user_id"], unique=False)
    op.create_table(
        "education",
        sa.Column("institution", sa.String(length=200), nullable=False),
        sa.Column("degree", sa.String(length=160), nullable=True),
        sa.Column("field", sa.String(length=160), nullable=True),
        sa.Column("start_year", sa.Integer(), nullable=True),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("grade", sa.String(length=48), nullable=True),
        sa.Column(
            "honors",
            postgresql.ARRAY(sa.String(length=160)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending_review", nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column("extracted_by", sa.String(length=120), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "user_corrected",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('resume','user_manual','jd','session_transcript','user_note','inference')",
            name=op.f("ck_education_education_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft','pending_review','approved','rejected','superseded')",
            name=op.f("ck_education_education_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_education_education_confidence_range"),
        ),
        sa.CheckConstraint(
            "end_year IS NULL OR start_year IS NULL OR end_year >= start_year",
            name=op.f("ck_education_education_year_order"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_education_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_education")),
    )
    op.create_index(op.f("ix_education_created_at"), "education", ["created_at"], unique=False)
    op.create_index(op.f("ix_education_status"), "education", ["status"], unique=False)
    op.create_index(op.f("ix_education_user_id"), "education", ["user_id"], unique=False)
    op.create_table(
        "experiences",
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("employment_type", sa.String(length=32), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("is_remote", sa.Boolean(), nullable=True),
        sa.Column("start_month", sa.Date(), nullable=True),
        sa.Column("end_month", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("date_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "bullets", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("seniority", sa.String(length=32), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending_review", nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column("extracted_by", sa.String(length=120), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "user_corrected",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('resume','user_manual','jd','session_transcript','user_note','inference')",
            name=op.f("ck_experiences_experiences_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft','pending_review','approved','rejected','superseded')",
            name=op.f("ck_experiences_experiences_status_valid"),
        ),
        sa.CheckConstraint(
            "NOT (is_current AND end_month IS NOT NULL)",
            name=op.f("ck_experiences_experiences_current_has_no_end"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_experiences_experiences_confidence_range"),
        ),
        sa.CheckConstraint(
            "end_month IS NULL OR start_month IS NULL OR end_month >= start_month",
            name=op.f("ck_experiences_experiences_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_experiences_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiences")),
    )
    op.create_index(op.f("ix_experiences_created_at"), "experiences", ["created_at"], unique=False)
    op.create_index(op.f("ix_experiences_status"), "experiences", ["status"], unique=False)
    op.create_index(op.f("ix_experiences_user_id"), "experiences", ["user_id"], unique=False)
    op.create_index(
        "ix_experiences_user_status",
        "experiences",
        ["user_id", "status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_experiences_user_timeline",
        "experiences",
        ["user_id", "start_month"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "graph_embeddings",
        sa.Column("entity_type", sa.String(length=24), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
        sa.Column("text_projection", sa.Text(), nullable=False),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', text_projection)", persisted=True),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_graph_embeddings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_embeddings")),
        sa.UniqueConstraint("entity_type", "entity_id", "model", name="uq_graph_embeddings_entity"),
    )
    op.create_index(
        op.f("ix_graph_embeddings_created_at"), "graph_embeddings", ["created_at"], unique=False
    )
    op.create_index(
        "ix_graph_embeddings_tsv", "graph_embeddings", ["tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        op.f("ix_graph_embeddings_user_id"), "graph_embeddings", ["user_id"], unique=False
    )
    op.create_index(
        "ix_graph_embeddings_user_type",
        "graph_embeddings",
        ["user_id", "entity_type"],
        unique=False,
    )
    op.create_index(
        "ix_graph_embeddings_vector",
        "graph_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 200},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "skills",
        sa.Column("canonical_name", sa.String(length=120), nullable=False),
        sa.Column("raw_name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=48), nullable=True),
        sa.Column("proficiency", sa.String(length=24), nullable=True),
        sa.Column("years_experience", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("last_used_year", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending_review", nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column("extracted_by", sa.String(length=120), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "user_corrected",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('resume','user_manual','jd','session_transcript','user_note','inference')",
            name=op.f("ck_skills_skills_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft','pending_review','approved','rejected','superseded')",
            name=op.f("ck_skills_skills_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_skills_skills_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_skills_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
        sa.UniqueConstraint("user_id", "canonical_name", name="uq_skills_user_canonical"),
    )
    op.create_index(op.f("ix_skills_created_at"), "skills", ["created_at"], unique=False)
    op.create_index(op.f("ix_skills_status"), "skills", ["status"], unique=False)
    op.create_index(op.f("ix_skills_user_id"), "skills", ["user_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("experience_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=160), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_month", sa.Date(), nullable=True),
        sa.Column("end_month", sa.Date(), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column(
            "technologies",
            postgresql.ARRAY(sa.String(length=80)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("impact", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending_review", nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column("extracted_by", sa.String(length=120), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "user_corrected",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('resume','user_manual','jd','session_transcript','user_note','inference')",
            name=op.f("ck_projects_projects_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft','pending_review','approved','rejected','superseded')",
            name=op.f("ck_projects_projects_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_projects_projects_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["experience_id"],
            ["experiences.id"],
            name=op.f("fk_projects_experience_id_experiences"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_projects_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_created_at"), "projects", ["created_at"], unique=False)
    op.create_index(op.f("ix_projects_experience_id"), "projects", ["experience_id"], unique=False)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_index(
        "ix_projects_user",
        "projects",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_table(
        "skill_links",
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=24), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "entity_type IN ('experience','project','achievement')",
            name=op.f("ck_skill_links_skill_links_entity_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_skill_links_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "skill_id", "entity_type", "entity_id", name=op.f("pk_skill_links")
        ),
    )
    op.create_index(
        "ix_skill_links_entity", "skill_links", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "achievements",
        sa.Column("experience_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "has_quantified_metric", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("metric_source_span", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending_review", nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column("extracted_by", sa.String(length=120), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "user_corrected",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('resume','user_manual','jd','session_transcript','user_note','inference')",
            name=op.f("ck_achievements_achievements_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft','pending_review','approved','rejected','superseded')",
            name=op.f("ck_achievements_achievements_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_achievements_achievements_confidence_range"),
        ),
        sa.CheckConstraint(
            "experience_id IS NOT NULL OR project_id IS NOT NULL",
            name=op.f("ck_achievements_achievements_require_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["experience_id"],
            ["experiences.id"],
            name=op.f("fk_achievements_experience_id_experiences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_achievements_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_achievements_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievements")),
    )
    op.create_index(
        op.f("ix_achievements_created_at"), "achievements", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_achievements_experience_id"), "achievements", ["experience_id"], unique=False
    )
    op.create_index(
        op.f("ix_achievements_project_id"), "achievements", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_achievements_status"), "achievements", ["status"], unique=False)
    op.create_index(op.f("ix_achievements_user_id"), "achievements", ["user_id"], unique=False)
    op.create_index(
        "ix_achievements_user_quantified",
        "achievements",
        ["user_id", "has_quantified_metric"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_achievements_user_quantified",
        table_name="achievements",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_achievements_user_id"), table_name="achievements")
    op.drop_index(op.f("ix_achievements_status"), table_name="achievements")
    op.drop_index(op.f("ix_achievements_project_id"), table_name="achievements")
    op.drop_index(op.f("ix_achievements_experience_id"), table_name="achievements")
    op.drop_index(op.f("ix_achievements_created_at"), table_name="achievements")
    op.drop_table("achievements")
    op.drop_index("ix_skill_links_entity", table_name="skill_links")
    op.drop_table("skill_links")
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_index(
        "ix_projects_user", table_name="projects", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_experience_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_created_at"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_skills_user_id"), table_name="skills")
    op.drop_index(op.f("ix_skills_status"), table_name="skills")
    op.drop_index(op.f("ix_skills_created_at"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(
        "ix_graph_embeddings_vector",
        table_name="graph_embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 200},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_graph_embeddings_user_type", table_name="graph_embeddings")
    op.drop_index(op.f("ix_graph_embeddings_user_id"), table_name="graph_embeddings")
    op.drop_index("ix_graph_embeddings_tsv", table_name="graph_embeddings", postgresql_using="gin")
    op.drop_index(op.f("ix_graph_embeddings_created_at"), table_name="graph_embeddings")
    op.drop_table("graph_embeddings")
    op.drop_index(
        "ix_experiences_user_timeline",
        table_name="experiences",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_experiences_user_status",
        table_name="experiences",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_experiences_user_id"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_status"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_created_at"), table_name="experiences")
    op.drop_table("experiences")
    op.drop_index(op.f("ix_education_user_id"), table_name="education")
    op.drop_index(op.f("ix_education_status"), table_name="education")
    op.drop_index(op.f("ix_education_created_at"), table_name="education")
    op.drop_table("education")
    op.drop_index(op.f("ix_certifications_user_id"), table_name="certifications")
    op.drop_index(op.f("ix_certifications_status"), table_name="certifications")
    op.drop_index(op.f("ix_certifications_created_at"), table_name="certifications")
    op.drop_table("certifications")
    op.drop_index(
        "ix_candidate_stories_user_status",
        table_name="candidate_stories",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_candidate_stories_user_id"), table_name="candidate_stories")
    op.drop_index(op.f("ix_candidate_stories_status"), table_name="candidate_stories")
    op.drop_index(op.f("ix_candidate_stories_created_at"), table_name="candidate_stories")
    op.drop_index(
        "ix_candidate_stories_categories", table_name="candidate_stories", postgresql_using="gin"
    )
    op.drop_table("candidate_stories")
    op.drop_index(op.f("ix_candidate_profiles_user_id"), table_name="candidate_profiles")
    op.drop_index(op.f("ix_candidate_profiles_created_at"), table_name="candidate_profiles")
    op.drop_table("candidate_profiles")
    # ### end Alembic commands ###
