"""live sessions detection and suggestions

Revision ID: 05c0d4cc2463
Revises: 5ca6ea8ad93d
Create Date: 2026-08-16 13:24:21.021618+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "05c0d4cc2463"
down_revision: str | None = "5ca6ea8ad93d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_events",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=48), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_events")),
        sa.UniqueConstraint("session_id", "seq", name="uq_session_events_session_seq"),
    )
    op.create_index(
        "ix_session_events_replay", "session_events", ["session_id", "seq"], unique=False
    )
    op.create_table(
        "detected_questions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("session_kind", sa.String(length=8), server_default="live", nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("speaker_id", sa.UUID(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("framework", sa.String(length=24), nullable=True),
        sa.Column(
            "sub_parts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("detection_confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("classification_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "signals",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("lifecycle_state", sa.String(length=16), nullable=False),
        sa.Column("detected_at_ms", sa.Integer(), nullable=False),
        sa.Column("finalized_at_ms", sa.Integer(), nullable=True),
        sa.Column("trigger", sa.String(length=8), server_default="auto", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "trigger IN ('auto','manual')",
            name=op.f("ck_detected_questions_detected_questions_trigger_valid"),
        ),
        sa.CheckConstraint(
            "detection_confidence >= 0 AND detection_confidence <= 1",
            name=op.f("ck_detected_questions_detected_questions_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_detected_questions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detected_questions")),
    )
    op.create_index(
        op.f("ix_detected_questions_created_at"), "detected_questions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_detected_questions_session_id"), "detected_questions", ["session_id"], unique=False
    )
    op.create_index(
        "ix_detected_questions_timeline",
        "detected_questions",
        ["session_id", "detected_at_ms"],
        unique=False,
    )
    op.create_index(
        op.f("ix_detected_questions_user_id"), "detected_questions", ["user_id"], unique=False
    )
    op.create_table(
        "session_speakers",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=8), nullable=False),
        sa.Column("provider_speaker_tag", sa.String(length=32), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "channel IN ('mic','system')",
            name=op.f("ck_session_speakers_session_speakers_channel_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_session_speakers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_speakers")),
        sa.UniqueConstraint(
            "session_id", "channel", "provider_speaker_tag", name="uq_session_speakers_identity"
        ),
    )
    op.create_index(
        op.f("ix_session_speakers_user_id"), "session_speakers", ["user_id"], unique=False
    )
    op.create_table(
        "ai_suggestions",
        sa.Column("detected_question_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("response_mode", sa.String(length=24), nullable=False),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "revision_reason", sa.String(length=24), server_default="initial", nullable=False
        ),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "evidence_ids",
            postgresql.ARRAY(sa.String(length=64)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "grounding",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("prompt_ref", sa.String(length=120), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("provider", sa.String(length=48), nullable=True),
        sa.Column(
            "latency_ms",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("degraded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("degraded_reason", sa.String(length=64), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("shown_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["detected_question_id"],
            ["detected_questions.id"],
            name=op.f("fk_ai_suggestions_detected_question_id_detected_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_suggestions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_suggestions")),
        sa.UniqueConstraint(
            "detected_question_id", "revision", name="uq_ai_suggestions_question_revision"
        ),
    )
    op.create_index(
        op.f("ix_ai_suggestions_created_at"), "ai_suggestions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ai_suggestions_detected_question_id"),
        "ai_suggestions",
        ["detected_question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_suggestions_session_id"), "ai_suggestions", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_ai_suggestions_user_id"), "ai_suggestions", ["user_id"], unique=False)
    op.create_table(
        "live_sessions",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("interview_type", sa.String(length=24), nullable=False),
        sa.Column(
            "integrity_mode", sa.String(length=16), server_default="assisted", nullable=False
        ),
        sa.Column("language", sa.String(length=20), server_default="en-US", nullable=False),
        sa.Column("response_mode", sa.String(length=24), server_default="balanced", nullable=False),
        sa.Column("stt_provider", sa.String(length=48), nullable=True),
        sa.Column(
            "llm_route",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), server_default="created", nullable=False),
        sa.Column("degraded_reason", sa.String(length=64), nullable=True),
        sa.Column("audio_retention", sa.String(length=16), server_default="none", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("last_event_seq", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("context_version", sa.Integer(), nullable=True),
        sa.Column("metered_seconds", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("generation_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "audio_retention IN ('none','session','30d')",
            name=op.f("ck_live_sessions_live_sessions_retention_valid"),
        ),
        sa.CheckConstraint(
            "integrity_mode IN ('assisted','proctored')",
            name=op.f("ck_live_sessions_live_sessions_integrity_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_live_sessions_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_live_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_live_sessions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_live_sessions")),
    )
    op.create_index(
        op.f("ix_live_sessions_created_at"), "live_sessions", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_live_sessions_user_id"), "live_sessions", ["user_id"], unique=False)
    op.create_index(
        "ix_live_sessions_user_recent",
        "live_sessions",
        ["user_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_live_sessions_workspace_id"), "live_sessions", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_live_sessions_workspace_id"), table_name="live_sessions")
    op.drop_index(
        "ix_live_sessions_user_recent",
        table_name="live_sessions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_live_sessions_user_id"), table_name="live_sessions")
    op.drop_index(op.f("ix_live_sessions_created_at"), table_name="live_sessions")
    op.drop_table("live_sessions")
    op.drop_index(op.f("ix_ai_suggestions_user_id"), table_name="ai_suggestions")
    op.drop_index(op.f("ix_ai_suggestions_session_id"), table_name="ai_suggestions")
    op.drop_index(op.f("ix_ai_suggestions_detected_question_id"), table_name="ai_suggestions")
    op.drop_index(op.f("ix_ai_suggestions_created_at"), table_name="ai_suggestions")
    op.drop_table("ai_suggestions")
    op.drop_index(op.f("ix_session_speakers_user_id"), table_name="session_speakers")
    op.drop_table("session_speakers")
    op.drop_index(op.f("ix_detected_questions_user_id"), table_name="detected_questions")
    op.drop_index("ix_detected_questions_timeline", table_name="detected_questions")
    op.drop_index(op.f("ix_detected_questions_session_id"), table_name="detected_questions")
    op.drop_index(op.f("ix_detected_questions_created_at"), table_name="detected_questions")
    op.drop_table("detected_questions")
    op.drop_index("ix_session_events_replay", table_name="session_events")
    op.drop_table("session_events")
    # ### end Alembic commands ###
