"""Unified embedding index for graph retrieval (PRD §12.3, §24.3).

One table covers every entity type so a single query can rank experiences,
projects, achievements and stories together. Storing embeddings beside the
relational rows lets an entity write and its index update share a transaction,
which is what makes deletion propagation exact (PRD FR-WS-010, §29.4).
"""

from __future__ import annotations

import uuid
from enum import StrEnum
from typing import Any

from pgvector.sqlalchemy import Vector
from sqlalchemy import Computed, Index, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from verity.platform.config import settings
from verity.platform.db.base import Base, Timestamped, UserOwned, UUIDPrimaryKey


class EntityType(StrEnum):
    """Retrievable node kinds. Typed retrieval filters on these (PRD §12.3)."""

    EXPERIENCE = "experience"
    PROJECT = "project"
    SKILL = "skill"
    ACHIEVEMENT = "achievement"
    EDUCATION = "education"
    CERTIFICATION = "certification"
    STORY = "story"


class GraphEmbedding(Base, UUIDPrimaryKey, Timestamped, UserOwned):
    __tablename__ = "graph_embeddings"

    entity_type: Mapped[str] = mapped_column(String(24), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(nullable=False)

    # Guards against re-embedding unchanged text — the dominant avoidable
    # embedding cost during re-extraction (PRD §33).
    content_hash: Mapped[bytes] = mapped_column(nullable=False)
    model: Mapped[str] = mapped_column(String(120), nullable=False)

    embedding: Mapped[Any] = mapped_column(Vector(settings.embedding_dimensions), nullable=False)

    #: Canonicalized projection actually embedded — kept so retrieval results are
    #: explainable and so re-embedding after a model change needs no re-read of
    #: the source rows.
    text_projection: Mapped[str] = mapped_column(Text, nullable=False)

    #: Lexical half of hybrid search (PRD FR-SRCH-002). Generated by Postgres so
    #: it can never drift from ``text_projection``.
    tsv: Mapped[Any] = mapped_column(
        TSVECTOR,
        Computed("to_tsvector('simple', text_projection)", persisted=True),
        nullable=False,
    )

    __table_args__ = (
        UniqueConstraint("entity_type", "entity_id", "model", name="uq_graph_embeddings_entity"),
        Index(
            "ix_graph_embeddings_vector",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 200},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        Index("ix_graph_embeddings_tsv", "tsv", postgresql_using="gin"),
        Index("ix_graph_embeddings_user_type", "user_id", "entity_type"),
    )
